Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,18 +16,4 @@ jobs:
         id: http
         run: | 
           CODE=`curl  -i -s "https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjOGU1MzFkYTgyNDZjNGVhN2E1Y2U1MGM2ODkzZmFmMGYiLCJpZCI6IjIxNDI4MSJ9.osogZm3Pv3Rzxhs9pd-OGtzZ9bIK-FJKXgeENnfZtQwuv9EZBu_d_lNE6nJmbgGvy-WXzYLIW9oK0vy_9D5c_gZ9uL2lxUTVJXfSw6XGNdt-D7l9meStn_-HG5YJK3eVSdUN2EFwuHbUHtPt-zjMtn-TW5wzXfpsFqCEETYgFj4" |grep HTTP|awk '{print $2}'`  >> $GITHUB_OUTPUT
-          if [ $CODE != "200" ]
-          then
-          echo "FAILURE"
-          else
-          echo "SUCCESS"
-          fi
-      - name: ckeck HTTP
-        run: echo ${{ steps.http.outputs.code }}
-        
-      - name: Generate 0 or 1
-        id: generate_number
-        run:  echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
-      - name: Pass or fail
-        run: |
-          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then exit 0; else exit 1; fi
+          if [ $CODE == "200" ];then echo "SUCCESS"; else echo "FAILURE" exit 1; fi
